spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
    password: system
  jpa:
    show-sql: true
    generate-ddl: false
 
eureka:
  client:
    register-with-eureka: true    
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9091